name: SoulPact-Coalition
version: '${version}'
main: bm.b0b0b0.SoulPact.coalition.SoulPactCoalitionPlugin
api-version: '1.21'
depend: [SoulPact]
softdepend: [SoulPact-War, SoulPact-Bank]
commands:
  clancoalition:
    description: Clan coalitions
    usage: /clancoalition
    aliases: [coalition, coa]
