order:
  - leader
  - deputy
  - officer
  - member
roles:
  leader:
    title: "<#F472B6>Капитан"
    list-names: true
  deputy:
    title: "<#C084FC>Вице-капитан"
    list-names: true
  officer:
    title: "<white>Командир"
    list-names: true
  member:
    title: "<white>Накама"
    list-names: false
