order:
  - leader
  - deputy
  - officer
  - member
roles:
  leader:
    title: "<#F472B6>Captain"
    list-names: true
  deputy:
    title: "<#C084FC>Vice Captain"
    list-names: true
  officer:
    title: "<white>Commander"
    list-names: true
  member:
    title: "<white>Nakama"
    list-names: false
