order:
  - leader
  - deputy
  - officer
  - member
roles:
  leader:
    title: "<#FCD34D>Генерал"
    list-names: true
  deputy:
    title: "<#C084FC>Полковник"
    list-names: true
  officer:
    title: "<white>Капитан"
    list-names: true
  member:
    title: "<white>Солдаты"
    list-names: false
