order:
  - leader
  - deputy
  - officer
  - member
roles:
  leader:
    title: "<#FCD34D>General"
    list-names: true
  deputy:
    title: "<#C084FC>Colonel"
    list-names: true
  officer:
    title: "<white>Captain"
    list-names: true
  member:
    title: "<white>Soldiers"
    list-names: false
