order:
  - leader
  - deputy
  - officer
  - member
roles:
  leader:
    title: "<#FCD34D>Генерал"
    list-names: true
  deputy:
    title: "<#D8B4FE>Полковник"
    list-names: true
  officer:
    title: "<#93C5FD>Капитан"
    list-names: true
  member:
    title: "<#9CA3AF>Солдаты"
    list-names: false
