locale: ru
fallback-locale: en
region-buffer: 5
base-radius: 8
border-material: RED_WOOL
border-colors:
  - RED_WOOL
  - ORANGE_WOOL
  - YELLOW_WOOL
  - LIME_WOOL
  - GREEN_WOOL
  - CYAN_WOOL
  - LIGHT_BLUE_WOOL
  - BLUE_WOOL
  - PURPLE_WOOL
  - MAGENTA_WOOL
  - PINK_WOOL
  - WHITE_WOOL
  - LIGHT_GRAY_WOOL
  - GRAY_WOOL
  - BLACK_WOOL
  - BROWN_WOOL
expansion:
  step: 8
  max-extent: 32
  base-cost: 1000
  cost-per-block: 250
gui:
  rows: 4
  slots:
    info: 4
    expand-north: 1
    expand-west: 9
    expand-east: 17
    expand-south: 25
    pvp: 20
    mob-spawn: 22
    border-color: 24
    back: 31
