name: SoulPact-War
version: '${version}'
main: bm.b0b0b0.SoulPact.war.SoulPactWarPlugin
api-version: '1.21'
depend: [SoulPact, SoulPact-Lands]
libraries:
  - net.elytrium:serializer:1.1.1
softdepend: [SoulPact-Bank, SoulPact-Chest]
commands:
  clanwar:
    description: Clan war declarations
    usage: /clanwar
    aliases: [cwar, war]
